### ISSUE TITLE
cond

### ISSUE THREAD

**Issue by syrflover** [rudty/nodekell#5]
cond 타입이 이게 맞는 건지 궁금해요

```ts
cond(
    boolean, value,
    () => boolean, value,
    Promise<boolean>, value,
    () => Promise<boolean>, value,
) => value
```

**Comment by rudty** [comment]
내부적으로 함수 호출은 하고있지 않으므로 

```javascript
cond(
    boolean, value,
    Promise<boolean>, value,
) => value
```
가 어떨까 합니다

api 명세 보고 반영한 lisp 의 cond의 명세에서는
```lisp
(cond   (test1 action1)
   (test2 action2)
   ...
   (testN actionN))
```
로 되어있는데요 

이걸 clojure에서 실행하게 되면 ([https://repl.it/languages/clojure](https://repl.it/languages/clojure))
실제로는 false, nil이 아닌 test에 대해서는 전부 action을 반환하고 있습니다 

```clojure
(cond "1" "1")
```
=> "1"

```clojure
(cond false "1")
```
=> nil

함수 호출에 대해서는 표현식이 true를 반환하고 있지만 실제로 호출되지는 않은 것으로 확인됩니다
```clojure
(defn foo []
	    (print "world"))
(cond foo "hello")
"world"는 출력하지 않음 
```

다만 0을 넣어도 true를 반환하고 있지만  
```clojure
(cond 0 "1")
```
=> "1"

자바스크립트 구조상 NaN, undefined, null, false 체크를 계속 한다면 매우 느려질수 있기에.. 
bool, Promise<bool> 타입에 대해서만, 추가한다면 otherwise 타입인 ()=>bool 이나 any를 를 추가할수 있을것 같습니다


만약 bool 형식에 대해서만 등록 하신다면 otherwise는 그냥 true로 변경하는것으로
cond에 대응할 수 있을것 같습니다

**Comment by syrflover** [comment]
이렇게까지 자세한 설명을...

궁금증이 풀렸습니다

감사합니다
